sudo: true

os:
 - linux
 - osx

env:
 - DB=mysql
 - DB=sqlite

install:
  - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "mysql" ]]; then brew update > /dev/null; fi
  - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "mysql" ]]; then brew install mysql && mysql.server start; fi
  - make install

before_script:
 - sqlite3 -version
 - cat /etc/my.cnf
 - cat /private/etc/my.cnf

script:
 - make YEAR=FY_2016
 - make schemas/${DB}_FY_2016.sql
 - tail -n+11 schemas/${DB}_FY_2016.sql
 - make $DB USER=root PASSFLAG=
 - make $DB YEAR=FY_2012 USER=root PASSFLAG=

after_sucess:
 - make -n $DB YEAR=FY_2013
 - make -n $DB YEAR=FY_2012
 - make -n $DB YEAR=FY_2011

matrix:
  allow_failures:
    -
        env: DB=sqlite
        os: linux
