sudo: true

os:
 - linux
 - osx

env:
 - DB=mysql
 - DB=sqlite

install:
  - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "mysql" ]]; then brew update > /dev/null; fi
  - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "mysql" ]]; then brew install mysql && mysql.server start; fi
  - make install

before_script:
 - sqlite3 -version

script:
 - make
 - head -n 800000 avroll_16.csv > _.csv && mv _.csv avroll_16.csv
 - head -n 12 avroll_16.csv
 - make schema-mysql.sql
 - head -n 13 schema-mysql.sql
 - make $DB USER=root PASSFLAG=
 - make $DB YEAR=all_10 USER=root PASSFLAG=

matrix:
  allow_failures:
    -
        env: DB=sqlite
        os: linux
