sudo: true

os:
 - linux
 - osx

env:
 - DB=mysql
 - DB=sqlite

install:
  - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "mysql" ]]; then brew update > /dev/null; fi
  - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "mysql" ]]; then brew install mysql && mysql.server start; fi
  - make install

script:
 - make avroll.csv
 - head -n 800000 avroll.csv > avroll1.csv && mv avroll1.csv avroll.csv
 - head -n 12 avroll.csv
 - make $DB USER=root PASSFLAG=

matrix:
  allow_failures:
    - env: DB=sqlite
