sudo: true

os:
 - linux
 - osx

env:
 - DB=mysql
 - DB=sqlite
 - DB=postgresql

addons:
  postgresql: 9.3

install:
  - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "mysql" ]]; then brew update > /dev/null; fi
  - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "mysql" ]]; then brew install mysql && mysql.server start; fi
  - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "sqlite" ]]; then brew install sqlite; fi
  - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "sqlite" ]]; then export SQLITE=/usr/local/opt/sqlite/bin/sqlite3; else export SQLITE=sqlite3; fi
  - if [[ $DB == "mysql" ]]; then export USER=root; fi
  - if [[ $DB == "postgresql" ]]; then export USER=postgres; fi
  - make install

before_script:
 - which $SQLITE
 - $SQLITE -version
 - cat /etc/my.cnf /etc/mysql/my.cnf /usr/local/mysql/etc/my.cnf ~/.my.cnf || echo

# for loop shortens CSV files to speed up loading tasks

script:
 - make FY_2016_TC2.csv FY_2016_TC1.csv FY_2016_condensed.csv YEAR=FY_2016 
 - for file in *.csv; do mv $file $file.bak; head -n 10000 $file.bak > $file ; done;
 - make ${DB}_FY_2016_tc.sql
 - make $DB YEAR=FY_2016 SQLITE=$SQLITE USER=$USER PASSFLAG=
 - make -n $DB-complete YEAR=FY_2014 SQLITE=$SQLITE USER=$USER PASSFLAG=
 - make -n $DB YEAR=FY_2013 SQLITE=$SQLITE USER=$USER PASSFLAG=
 - make -n $DB-condensed YEAR=FY_2011 SQLITE=$SQLITE USER=$USER PASSFLAG=

after_success:
 - make check-$DB YEAR=FY_2016 SQLITE=$SQLITE USER=$USER PASSFLAG=

matrix:
  allow_failures:
    -
        env: DB=postgresql
    -
        env: DB=sqlite
        os: linux
    -
        env: DB=mysql
        os: osx

  exclude:
    -
        env: DB=postgresql
        os: osx
