sudo: true

os:
 - linux
 - osx

env:
 - DB=mysql
 - DB=sqlite

install:
  - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "mysql" ]]; then brew update > /dev/null; fi
  - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "mysql" ]]; then brew install mysql && mysql.server start; fi
  - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "sqlite" ]]; then brew install sqlite; fi
  - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "sqlite" ]]; then export SQLITE=/usr/local/opt/sqlite/bin/sqlite3; else export SQLITE=sqlite3; fi
  - if [[ $DB == "mysql" ]]; then export USER=root; fi
  - make install

before_script:
 - which $SQLITE
 - $SQLITE -version

script:
 - make YEAR=FY_2016
 - make ${DB}_FY_2016_tc.sql
 - tail -n+11 ${DB}_FY_2016_tc.sql
 - make $DB SQLITE=$SQLITE USER=$USER PASSFLAG=
 - make -n $DB YEAR=FY_2012 SQLITE=$SQLITE USER=$USER PASSFLAG=
 - make -n $DB-complete YEAR=FY_2014 SQLITE=$SQLITE USER=$USER PASSFLAG=
 - make -n $DB YEAR=FY_2013 SQLITE=$SQLITE USER=$USER PASSFLAG=
 - make -n $DB-condensed YEAR=FY_2011 SQLITE=$SQLITE USER=$USER PASSFLAG=

matrix:
  allow_failures:
    -
        env: DB=sqlite
        os: linux
